SKILLS = [
    "Python",
    "Java",
    "C",
    "C++",
    "C#",
    "JavaScript",
    "TypeScript",
    "SQL",
    "HTML",
    "HTML5",
    "CSS",
    "CSS3",
    "React",
    "Node.js",
    "Flask",
    "FastAPI",
    "Django",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "NLP",
    "PyTorch",
    "TensorFlow",
    "scikit-learn",
    "Pandas",
    "NumPy",
    "spaCy",
    "BeautifulSoup",
    "Git",
    "GitHub",
    "Docker",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "AWS",
    "Azure",
    "GCP",
    "Power BI",
    "Tableau",
    "Excel",
]
