SKILLS = [
    "Python",
    "Java",
    "C++",
    "C#",
    "JavaScript",
    "TypeScript",
    "SQL",
    "HTML",
    "HTML5",
    "CSS",
    "CSS3",
    "React",
    "Node.js",
    "Flask",
    "FastAPI",
    "Django",
    "REST APIs",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Generative AI",
    "Prompt Engineering",
    "NLP",
    "PyTorch",
    "TensorFlow",
    "scikit-learn",
    "Pandas",
    "NumPy",
    "spaCy",
    "BeautifulSoup",
    "OpenAI",
    "Git",
    "GitHub",
    "Docker",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "AWS",
    "Azure",
    "GCP",
    "Power BI",
    "Tableau",
    "Excel",
    "JIRA",
    "Postman",
    "VS Code",
    "Jupyter Notebook",
    "Data Analysis",
    "Data Structures & Algorithms",
]

SKILLS_LOWER = {skill.lower() for skill in SKILLS}
SKILL_LOOKUP = {skill.lower(): skill for skill in SKILLS}
